not_hotdog/api/urls.py
from django.urls import path
from . import views
 

urlpatterns = [

    path('photos/', views.PhotoList.as_view()), # to see all listed photos

    path('get_detail/<int:pk>/', views.PhotoDetailGetView.as_view()), # to see the detail of one photo

    path('update_detail/<int:pk>/', views.PhotoDetailPutDeleteView.as_view()), # to change the detail
]

not_hotdog/not_hotdog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # main app
    path('photoapp/', include('photoapp.urls')),

    path('users/', include('users.urls')),

    # api-
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

not_hotdog/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from .views import SignUpView, CustomLoginView, ShowUserNameView


app_name = "user"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"), # custom view
    path("login/", CustomLoginView.as_view(), name="login"), # custom view
    path("logout/", LogoutView.as_view(), name="logout"), # Django built-in logout view
    path("display_users/", login_required(ShowUserNameView.as_view()), name="display_users"), # listing registered users
]

not_hotdog/users/views.py
from django.views.generic import CreateView, ListView
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm # to create a new user
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from django.shortcuts import render


# to allow the user to register through the site
class SignUpView(CreateView):
    template_name = 'users/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('photo:list')

    # log in the users before redirecting them to the photo dashboard
    def form_valid(self,form):
        to_return = super().form_valid(form)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        login(self.request, user)
        return to_return


class CustomLoginView(LoginView):
    template_name = "users/login.html"


class ShowUserNameView(ListView):
    model = User
    template_name = 'users/display_users.html'
    context_object_name = 'usernames'
    

not_hotdog/users/templates/users/display_users.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block body %}
  {% csrf_token %} 
  {{ form|crispy }}
  <center>
    <ul class="list-group"> <b>Registered Users:</b>
      <br>
      {% for user in usernames %}
      <li class="list-group-item">{{ user.username }}</li>
      {% endfor %}
    </ul>
  </center>
{% endblock body %}

not_hotdog/users/templates/users/login.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block body %}

<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Login</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Don't have an account?
      <a href="{% url 'user:signup' %}" class="text-primary ml-2">Create account</a>
    </p>
  </div>
</div>
{% endblock body %}

not_hotdog/users/templates/users/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block body %}
<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-danger w-100 my-3">Create account</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Already Registered?
      <a href="{% url 'user:login' %}" class="text-primary ml-2"> Login </a>
    </p>
  </div>
</div>
{% endblock body %}