not_hotdog/api/urls.py
from django.urls import path
from . import views
 

urlpatterns = [

    path('photos/', views.PhotoList.as_view()), # to see all listed photos

    path('get_detail/<int:pk>/', views.PhotoDetailGetView.as_view()), # to see the detail of one photo

    path('update_detail/<int:pk>/', views.PhotoDetailPutDeleteView.as_view()), # to change the detail
]

not_hotdog/not_hotdog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # main app
    path('photoapp/', include('photoapp.urls')),

    path('users/', include('users.urls')),

    # api-
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

not_hotdog/photoapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    PhotoListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    PhotoMyListView,
    UserPhotosDetailView,
    PhotoTagListView
)
    
# namespace of the app
app_name = 'photo'    
urlpatterns = [
    path('', PhotoListView.as_view(), name='list'),

    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),

    path('photo/create/', PhotoCreateView.as_view(), name='create'),

    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),

    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),

    path('photo/mylist/', login_required(PhotoMyListView.as_view()), name='mylist'),

    path('photo/tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),

    path('photo/myphotodetail/<int:pk>/', UserPhotosDetailView.as_view(), name='userphotosdetail'),

]

not_hotdog/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from .views import SignUpView, CustomLoginView, ShowUserNameView


app_name = "user"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"), # custom view
    path("login/", CustomLoginView.as_view(), name="login"), # custom view
    path("logout/", LogoutView.as_view(), name="logout"), # Django built-in logout view
    path("display_users/", login_required(ShowUserNameView.as_view()), name="display_users"), # listing registered users
]

not_hotdog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Not Hotdog</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar.html' %}

    <div class="container mt-4">{% block body %} {% endblock body %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

not_hotdog/templates/navbar.html
{% load static %}
<nav
  class="navbar navbar-expand-md navbar-dark"
  style="background-color: #0b193c"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'photo:list' %}"
      ><img
        src="{% static 'photoapp/logo.svg' %}"
        width="100"
        height="50"
        alt=""
    /></a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse flex-row-reverse"
      id="navbarTogglerDemo02"
    >
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'photo:create' %}">Upload</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'photo:mylist' %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'user:display_users' %}"
            >Users</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'user:logout' %}">Logout</a>
        </li>
        {% else %}

        <li class="nav-item">
          <a href="{% url 'user:login' %}" class="btn btn-sm btn-danger"
            >Login</a
          >
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>