not_hotdog/api/urls.py
from django.urls import path
from . import views
 

urlpatterns = [

    path('photos/', views.PhotoList.as_view()), # to see all listed photos

    path('get_detail/<int:pk>/', views.PhotoDetailGetView.as_view()), # to see the detail of one photo

    path('update_detail/<int:pk>/', views.PhotoDetailPutDeleteView.as_view()), # to change the detail
]

not_hotdog/not_hotdog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # main app
    path('photoapp/', include('photoapp.urls')),

    path('users/', include('users.urls')),

    # api-
    path('api/', include('api.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

not_hotdog/photoapp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    PhotoListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    PhotoMyListView,
    UserPhotosDetailView,
    PhotoTagListView
)
    
# namespace of the app
app_name = 'photo'    
urlpatterns = [
    path('', PhotoListView.as_view(), name='list'),

    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),

    path('photo/create/', PhotoCreateView.as_view(), name='create'),

    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),

    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),

    path('photo/mylist/', login_required(PhotoMyListView.as_view()), name='mylist'),

    path('photo/tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),

    path('photo/myphotodetail/<int:pk>/', UserPhotosDetailView.as_view(), name='userphotosdetail'),

]

not_hotdog/photoapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from api.send import send_message


class Photo(models.Model):
    title = models.CharField(max_length=45)
    description = models.CharField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='photos/')
    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = TaggableManager(blank=True) 
    not_hotdog_flag = models.BooleanField(null=True) # if not a hotdog = True


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        pk = self.pk
        photo = super().save(force_insert=False, force_update=False, using=None, update_fields=None)
        if pk is None: # if it was a newly created file, send a message
            send_message("New image uploaded", {
                "id": self.pk,
                "title": self.title,
                "not_hotdog_flag": self.not_hotdog_flag,
                "image": self.image.path,
            })
        return photo

not_hotdog/photoapp/views.py
# allows us to retrieve an object from the database, 
# preventing a DoesNotExists error and raising a HTTP 404 exception
from django.shortcuts import get_object_or_404
# aise an HTTP 403 exception when called
from django.core.exceptions import PermissionDenied
# for building CRUD functionality
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView
# to assert the users have the right permissions when accessing to a view
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# used in CBVs to redirect the users to a specific URL
from django.urls import reverse_lazy
# to retrieve and update database rows (photo objects)
from .models import Photo
# to make next and previous buttons
from next_prev import next_in_order, prev_in_order


# Listing all photos on the site
class PhotoListView(ListView):
    model = Photo
    template_name = 'photoapp/list.html'
    context_object_name = 'photos'
    

# showing photo tags
class PhotoTagListView(PhotoListView):
    template_name = 'photoapp/taglist.html'
    # custom method
    # receive the tag slug from the response Django is going to take and return it
    def get_tag(self):
        return self.kwargs.get('tag')

    def get_queryset(self):
        return self.model.objects.filter(tags__slug=self.get_tag())

    # return the tag passed to the URL
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.get_tag
        return context


# showing details of the photos
class PhotoDetailView(DetailView):
    model = Photo
    template_name = 'photoapp/detail.html'
    context_object_name = 'photo'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_obj = Photo.objects.get(id=self.kwargs['pk'])
        next = next_in_order(current_obj)
        previous = prev_in_order(current_obj)
        if next != None:
            context['next_pk'] = next.id
        else:
            context['next_pk'] = Photo.objects.first().id

        if previous != None:
            context['prev_pk'] = previous.id
        else:
            context['prev_pk'] = Photo.objects.last().id

        return context


# allows upload photos for registered users
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    # create a form with these fields
    fields = ['title', 'description', 'image', 'tags']
    template_name = 'photoapp/create.html'
    # Users will be redirected to the photo dashboard 
    # if the photo creation was successful
    success_url = reverse_lazy('photo:list')

    def form_valid(self, form):
        # setting up the user that’s making the request 
        # as the submitter of the photo form
        form.instance.submitter = self.request.user
        return super().form_valid(form)

    # def send_message_when_photo_uploaded(self, request):
    #     serializer = PhotoSerializer()
    #     publish('image uploaded', serializer.data)

# checks if the user that’s trying to update or delete a photo 
# actually submitted it
class UserIsSubmitter(UserPassesTestMixin):
    # custom method
    def get_photo(self):
        return get_object_or_404(Photo, pk=self.kwargs.get('pk'))

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')


# allows to ipdate photo for the creator
class PhotoUpdateView(UserIsSubmitter, UpdateView):
    template_name = 'photoapp/update.html'
    model = Photo
    # defines the fields the user will be able to edit
    fields = ['title', 'description', 'tags']
    success_url = reverse_lazy('photo:list')


class PhotoDeleteView(UserIsSubmitter, DeleteView):
    template_name = 'photoapp/delete.html'
    model = Photo
    success_url = reverse_lazy('photo:list')


# listing personal photos for registered users
class PhotoMyListView(ListView):
    model = Photo
    template_name = 'photoapp/mylist.html'
    context_object_name = 'myphotos'


# showing details of user photos, allows to swipe to user next photo
class UserPhotosDetailView(DetailView):
    model = Photo
    template_name = 'photoapp/userphotosdetail.html'
    context_object_name = 'userphoto'
    # only users photos must be in a queryset
    def get_queryset(self):
        return Photo.objects.filter(submitter=self.request.user.id)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_obj = Photo.objects.get(id=self.request.user.id)   
        next = next_in_order(current_obj)
        previous = prev_in_order(current_obj)
        if next != None:
            context['next_pk'] = next.id
        else:
            context['next_pk'] = Photo.objects.first().id

        if previous != None:
            context['prev_pk'] = previous.id
        else:
            context['prev_pk'] = Photo.objects.first().id
        return context

not_hotdog/photoapp/templates/photoapp/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Add photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>
{% endblock body %}

not_hotdog/photoapp/templates/photoapp/delete.html
{% extends 'base.html' %} 

{% block body %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ photo }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock body %}

not_hotdog/photoapp/templates/photoapp/detail.html
{% extends 'base.html' %} {% block body %}
<div class="mx-auto">
  <h1 class="text-center">{{ photo.title }}</h1>
  <p class="text-center fw-light">Photo detail:<br /></p>
  <p class="text-center fw-light">
    Uploaded on: {{photo.created}} <br />
    By {{photo.submitter.username}}
  </p>
  {% if user == photo.submitter %}
  <p class="text-center">
    <span
      ><a href="{% url 'photo:update' photo.id %}" class="text-primary px-2"
        >Edit</a
      ></span
    >
    <span
      ><a href="{% url 'photo:delete' photo.id %}" class="text-danger px-2"
        >Delete</a
      ></span
    >
  </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{photo.image.url}}" alt="" width="100%" />
  </div>
  <div class="col-md-4">
    <h4>Description:</h4>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      {% for tag in photo.tags.all %}
      <li>
        <a
          href="{% url 'photo:tag' tag.slug %}"
          class="btn btn-sm list-group-item list-group-item-primary"
          >{{tag.name}}</a
        >
      </li>
      {% endfor %}
    </ul>
    <p>{{ photo.description }}</p>
  </div>
  <div class="mx-auto">
    <p class="text-center">
      <span
        ><a href="{% url 'photo:detail' prev_pk %}" class="text-primary px-2"
          >Previous</a
        ></span
      >
      <span
        ><a href="{% url 'photo:detail' next_pk %}" class="text-danger px-2"
          >Next</a
        ></span
      >
    </p>
  </div>
</div>

{% endblock body %}

not_hotdog/photoapp/templates/photoapp/list.html
{% extends 'base.html' %} {% block body %}

<div class="row">
  {% if user.is_authenticated %} {% for photo in photos %}
  <div class="col-lg-3 col-md-4 col-xs-6">
    <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
      <img
        src="{{photo.image.url}}"
        class="img-fluid rounded"
        alt="{{photo.title}}"
      />
    </a>
  </div>
  {% endfor %} {% else %} {% for photo in photos %} {% if photo.not_hotdog_flag == False %}
  <div class="col-lg-3 col-md-4 col-xs-6">
    <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
      <img
        src="{{photo.image.url}}"
        class="img-fluid rounded"
        alt="{{photo.title}}"
      />
    </a>
  </div>
  {% endif %} {% endfor %} {% endif %}
</div>

{% endblock body %}

not_hotdog/photoapp/templates/photoapp/mylist.html
{% extends 'base.html' %} {% block body %}
<div class="row">
  <h1>{{ user.username }}:</h1>
  {% for photo in myphotos %} {% if photo.submitter.username == user.username %}
  <div class="col-lg-3 col-md-4 col-xs-6">
    <a
      href="{% url 'photo:userphotosdetail' photo.id  %}"
      class="d-block mb-4 h-100"
    >
      <img
        src="{{photo.image.url}}"
        class="img-fluid rounded"
        alt="{{photo.title}}"
      />
    </a>
  </div>

  {% endif %} {% empty %}
  <h1>No photos</h1>
  {% endfor %}
</div>
{% endblock body %}

not_hotdog/photoapp/templates/photoapp/taglist.html
{% extends 'photoapp/list.html' %} {% block body %}

<div class="alert alert-primary">
  <h2 class="text-center">Photos with the tag {{tag}}</h2>
</div>

{{ block.super }} {% endblock body %}

not_hotdog/photoapp/templates/photoapp/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock body %}

not_hotdog/photoapp/templates/photoapp/userphotosdetail.html
{% extends 'base.html' %} 

{% block body %}
<div class="mx-auto">
  <h1 class="text-center">{{ userphoto.title }}</h1>
  <p class="text-center fw-light">Photo detail:<br></p>
  <p class="text-center fw-light">Uploaded on: {{ userphoto.created }} <br> By {{photo.submitter.username}}</p>
  {% if user == userphoto.submitter %}
    <p class="text-center">
      <span><a href="{% url 'photo:update' userphoto.id %}" class="text-primary px-2">Edit</a></span>
      <span><a href="{% url 'photo:delete' userphoto.id %}" class="text-danger px-2">Delete</a></span>
    </p>
  {% endif %}
</div>
<div class="row pb-5">
  <div class="col-md-8">
    <img src="{{userphoto.image.url}}" alt="" width="100%" />
  </div>
  <div class="col-md-4">
    <h4>Description:</h4>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
    </ul>
    <p>{{ userphoto.description }}</p>
  </div>
{% if user.is_authenticated %}
  <div class="mx-auto">
      <p class="text-center">
        <span><a href="{% url 'photo:userphotosdetail' prev_pk %}" class="text-primary px-2">Previous</a></span>
        <span><a href="{% url 'photo:userphotosdetail' next_pk %}" class="text-danger px-2">Next</a></span>

      </p>
    </div> 
{% endif %}

</div>

{% endblock body %}